name: dokira_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.1.0

  # State Management
  provider: ^6.1.1

  # Stockage local
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^12.1.3

  # JSON Serialization
  json_annotation: ^4.8.1
  
  # WebView
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Pour Windows
  #webview_windows: ^0.3.0

  # Pour ouvrir URLs sur Windows/Web
  url_launcher: ^6.2.1

  # Pour Android 
  webview_flutter_android: ^3.12.1

  # Pour iOS
  webview_flutter_wkwebview: ^3.12.1

  # Pour JSON
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/